repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args:
          - '-l 100'

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        language_version: python3
        args: [ "--skip-gitignore", "--profile", "black" ]
