import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthProvider } from './state-managemnt/app-state-context'; 
import { DashboardProvider } from './state-managemnt/dashboard-state-context';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
          <AuthProvider>
          <DashboardProvider >

      <body className={inter.className}>{children}</body>
      {children}</DashboardProvider>
      </AuthProvider>

    </html>
  )
}
