name: frontend_futter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.0.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    flutter_hooks: ^0.18.6
    auto_route: ^7.4.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    build_runner: ^2.4.5
    auto_route_generator: ^7.1.1

flutter:
    uses-material-design: true
    assets:
      - assets/images/



