name: frontend_futter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.0.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter


    flutter_hooks: ^0.18.6
    auto_route: ^7.4.0
    dio: ^5.2.1+1
    retrofit: ^4.0.1
    meta: ^1.9.1
    flutter_bloc: ^8.1.3
    equatable: ^2.0.5
    bloc: ^8.1.2


dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    build_runner: ^2.4.5
    auto_route_generator: ^7.1.1
    retrofit_generator: ^7.0.1
    json_serializable: ^6.7.0

flutter:
    uses-material-design: true
    assets:
      - assets/images/




