name: cardpay
description: A new Flutter project.
publish_to: "none"
version: 1.2.34+45

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  flutter_hooks: ^0.18.6
  auto_route: ^7.4.0
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  meta: ^1.9.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  curved_navigation_bar: ^1.0.1
  get_it: ^7.6.0
  awesome_dio_interceptor: ^1.0.0
  logger: ^1.4.0
  intl: ^0.18.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  url_launcher: ^6.1.12
  skeleton_loader: ^2.0.0+4
  animated_bottom_navigation_bar: ^1.2.0
  qr_code_scanner: ^1.0.1
  local_auth: ^2.1.6
  google_fonts: ^5.1.0
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.5
  shared_preferences: ^2.2.0
  package_info_plus: ^4.1.0
  dio_smart_retry: ^5.0.0
  qr_flutter: ^4.1.0
  firebase_messaging: ^14.7.2
  floor: ^1.4.2
  # screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  auto_route_generator: ^7.1.1
  retrofit_generator: ^7.0.1
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/files/catalog.json
    - assets/files/faqs.json


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
